// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package music

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MusicServiceClient is the client API for MusicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MusicServiceClient interface {
	UploadTrack(ctx context.Context, in *UploadTrackRequest, opts ...grpc.CallOption) (*UploadTrackResponse, error)
	GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*Track, error)
	ListTracks(ctx context.Context, in *ListTracksRequest, opts ...grpc.CallOption) (*ListTracksResponse, error)
	SearchTracks(ctx context.Context, in *SearchTracksRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error)
	CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*Playlist, error)
	AddToPlaylist(ctx context.Context, in *AddToPlaylistRequest, opts ...grpc.CallOption) (*Playlist, error)
	RemoveFromPlaylist(ctx context.Context, in *RemoveFromPlaylistRequest, opts ...grpc.CallOption) (*Playlist, error)
	GetPlaylist(ctx context.Context, in *GetPlaylistRequest, opts ...grpc.CallOption) (*Playlist, error)
	GetUserPlaylists(ctx context.Context, in *GetUserPlaylistsRequest, opts ...grpc.CallOption) (*GetUserPlaylistsResponse, error)
	StreamTrack(ctx context.Context, in *StreamTrackRequest, opts ...grpc.CallOption) (MusicService_StreamTrackClient, error)
	GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*RecommendationsResponse, error)
	LikeTrack(ctx context.Context, in *LikeTrackRequest, opts ...grpc.CallOption) (*LikeTrackResponse, error)
	GetLikedTracks(ctx context.Context, in *GetLikedTracksRequest, opts ...grpc.CallOption) (*GetLikedTracksResponse, error)
	AddToQueue(ctx context.Context, in *AddToQueueRequest, opts ...grpc.CallOption) (*AddToQueueResponse, error)
	GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error)
}

type musicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMusicServiceClient(cc grpc.ClientConnInterface) MusicServiceClient {
	return &musicServiceClient{cc}
}

func (c *musicServiceClient) UploadTrack(ctx context.Context, in *UploadTrackRequest, opts ...grpc.CallOption) (*UploadTrackResponse, error) {
	out := new(UploadTrackResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/UploadTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*Track, error) {
	out := new(Track)
	err := c.cc.Invoke(ctx, "/music.MusicService/GetTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) ListTracks(ctx context.Context, in *ListTracksRequest, opts ...grpc.CallOption) (*ListTracksResponse, error) {
	out := new(ListTracksResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/ListTracks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) SearchTracks(ctx context.Context, in *SearchTracksRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error) {
	out := new(SearchTracksResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/SearchTracks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*Playlist, error) {
	out := new(Playlist)
	err := c.cc.Invoke(ctx, "/music.MusicService/CreatePlaylist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) AddToPlaylist(ctx context.Context, in *AddToPlaylistRequest, opts ...grpc.CallOption) (*Playlist, error) {
	out := new(Playlist)
	err := c.cc.Invoke(ctx, "/music.MusicService/AddToPlaylist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) RemoveFromPlaylist(ctx context.Context, in *RemoveFromPlaylistRequest, opts ...grpc.CallOption) (*Playlist, error) {
	out := new(Playlist)
	err := c.cc.Invoke(ctx, "/music.MusicService/RemoveFromPlaylist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetPlaylist(ctx context.Context, in *GetPlaylistRequest, opts ...grpc.CallOption) (*Playlist, error) {
	out := new(Playlist)
	err := c.cc.Invoke(ctx, "/music.MusicService/GetPlaylist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetUserPlaylists(ctx context.Context, in *GetUserPlaylistsRequest, opts ...grpc.CallOption) (*GetUserPlaylistsResponse, error) {
	out := new(GetUserPlaylistsResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/GetUserPlaylists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) StreamTrack(ctx context.Context, in *StreamTrackRequest, opts ...grpc.CallOption) (MusicService_StreamTrackClient, error) {
	stream, err := c.cc.NewStream(ctx, &MusicService_ServiceDesc.Streams[0], "/music.MusicService/StreamTrack", opts...)
	if err != nil {
		return nil, err
	}
	x := &musicServiceStreamTrackClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MusicService_StreamTrackClient interface {
	Recv() (*TrackChunk, error)
	grpc.ClientStream
}

type musicServiceStreamTrackClient struct {
	grpc.ClientStream
}

func (x *musicServiceStreamTrackClient) Recv() (*TrackChunk, error) {
	m := new(TrackChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *musicServiceClient) GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*RecommendationsResponse, error) {
	out := new(RecommendationsResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/GetRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) LikeTrack(ctx context.Context, in *LikeTrackRequest, opts ...grpc.CallOption) (*LikeTrackResponse, error) {
	out := new(LikeTrackResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/LikeTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetLikedTracks(ctx context.Context, in *GetLikedTracksRequest, opts ...grpc.CallOption) (*GetLikedTracksResponse, error) {
	out := new(GetLikedTracksResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/GetLikedTracks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) AddToQueue(ctx context.Context, in *AddToQueueRequest, opts ...grpc.CallOption) (*AddToQueueResponse, error) {
	out := new(AddToQueueResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/AddToQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error) {
	out := new(GetQueueResponse)
	err := c.cc.Invoke(ctx, "/music.MusicService/GetQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MusicServiceServer is the server API for MusicService service.
// All implementations must embed UnimplementedMusicServiceServer
// for forward compatibility
type MusicServiceServer interface {
	UploadTrack(context.Context, *UploadTrackRequest) (*UploadTrackResponse, error)
	GetTrack(context.Context, *GetTrackRequest) (*Track, error)
	ListTracks(context.Context, *ListTracksRequest) (*ListTracksResponse, error)
	SearchTracks(context.Context, *SearchTracksRequest) (*SearchTracksResponse, error)
	CreatePlaylist(context.Context, *CreatePlaylistRequest) (*Playlist, error)
	AddToPlaylist(context.Context, *AddToPlaylistRequest) (*Playlist, error)
	RemoveFromPlaylist(context.Context, *RemoveFromPlaylistRequest) (*Playlist, error)
	GetPlaylist(context.Context, *GetPlaylistRequest) (*Playlist, error)
	GetUserPlaylists(context.Context, *GetUserPlaylistsRequest) (*GetUserPlaylistsResponse, error)
	StreamTrack(*StreamTrackRequest, MusicService_StreamTrackServer) error
	GetRecommendations(context.Context, *GetRecommendationsRequest) (*RecommendationsResponse, error)
	LikeTrack(context.Context, *LikeTrackRequest) (*LikeTrackResponse, error)
	GetLikedTracks(context.Context, *GetLikedTracksRequest) (*GetLikedTracksResponse, error)
	AddToQueue(context.Context, *AddToQueueRequest) (*AddToQueueResponse, error)
	GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error)
	mustEmbedUnimplementedMusicServiceServer()
}

// UnimplementedMusicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMusicServiceServer struct {
}

func (UnimplementedMusicServiceServer) UploadTrack(context.Context, *UploadTrackRequest) (*UploadTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadTrack not implemented")
}
func (UnimplementedMusicServiceServer) GetTrack(context.Context, *GetTrackRequest) (*Track, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrack not implemented")
}
func (UnimplementedMusicServiceServer) ListTracks(context.Context, *ListTracksRequest) (*ListTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTracks not implemented")
}
func (UnimplementedMusicServiceServer) SearchTracks(context.Context, *SearchTracksRequest) (*SearchTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTracks not implemented")
}
func (UnimplementedMusicServiceServer) CreatePlaylist(context.Context, *CreatePlaylistRequest) (*Playlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlaylist not implemented")
}
func (UnimplementedMusicServiceServer) AddToPlaylist(context.Context, *AddToPlaylistRequest) (*Playlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToPlaylist not implemented")
}
func (UnimplementedMusicServiceServer) RemoveFromPlaylist(context.Context, *RemoveFromPlaylistRequest) (*Playlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromPlaylist not implemented")
}
func (UnimplementedMusicServiceServer) GetPlaylist(context.Context, *GetPlaylistRequest) (*Playlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaylist not implemented")
}
func (UnimplementedMusicServiceServer) GetUserPlaylists(context.Context, *GetUserPlaylistsRequest) (*GetUserPlaylistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPlaylists not implemented")
}
func (UnimplementedMusicServiceServer) StreamTrack(*StreamTrackRequest, MusicService_StreamTrackServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTrack not implemented")
}
func (UnimplementedMusicServiceServer) GetRecommendations(context.Context, *GetRecommendationsRequest) (*RecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedMusicServiceServer) LikeTrack(context.Context, *LikeTrackRequest) (*LikeTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeTrack not implemented")
}
func (UnimplementedMusicServiceServer) GetLikedTracks(context.Context, *GetLikedTracksRequest) (*GetLikedTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikedTracks not implemented")
}
func (UnimplementedMusicServiceServer) AddToQueue(context.Context, *AddToQueueRequest) (*AddToQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToQueue not implemented")
}
func (UnimplementedMusicServiceServer) GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueue not implemented")
}
func (UnimplementedMusicServiceServer) mustEmbedUnimplementedMusicServiceServer() {}

// UnsafeMusicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MusicServiceServer will
// result in compilation errors.
type UnsafeMusicServiceServer interface {
	mustEmbedUnimplementedMusicServiceServer()
}

func RegisterMusicServiceServer(s grpc.ServiceRegistrar, srv MusicServiceServer) {
	s.RegisterService(&MusicService_ServiceDesc, srv)
}

func _MusicService_UploadTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).UploadTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/UploadTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).UploadTrack(ctx, req.(*UploadTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetTrack(ctx, req.(*GetTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_ListTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).ListTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/ListTracks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).ListTracks(ctx, req.(*ListTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_SearchTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).SearchTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/SearchTracks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).SearchTracks(ctx, req.(*SearchTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_CreatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).CreatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/CreatePlaylist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).CreatePlaylist(ctx, req.(*CreatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_AddToPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).AddToPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/AddToPlaylist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).AddToPlaylist(ctx, req.(*AddToPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_RemoveFromPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).RemoveFromPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/RemoveFromPlaylist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).RemoveFromPlaylist(ctx, req.(*RemoveFromPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetPlaylist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetPlaylist(ctx, req.(*GetPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetUserPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetUserPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetUserPlaylists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetUserPlaylists(ctx, req.(*GetUserPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_StreamTrack_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTrackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MusicServiceServer).StreamTrack(m, &musicServiceStreamTrackServer{stream})
}

type MusicService_StreamTrackServer interface {
	Send(*TrackChunk) error
	grpc.ServerStream
}

type musicServiceStreamTrackServer struct {
	grpc.ServerStream
}

func (x *musicServiceStreamTrackServer) Send(m *TrackChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _MusicService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetRecommendations(ctx, req.(*GetRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_LikeTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).LikeTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/LikeTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).LikeTrack(ctx, req.(*LikeTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetLikedTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetLikedTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetLikedTracks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetLikedTracks(ctx, req.(*GetLikedTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_AddToQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).AddToQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/AddToQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).AddToQueue(ctx, req.(*AddToQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.MusicService/GetQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).GetQueue(ctx, req.(*GetQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MusicService_ServiceDesc is the grpc.ServiceDesc for MusicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MusicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "music.MusicService",
	HandlerType: (*MusicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadTrack",
			Handler:    _MusicService_UploadTrack_Handler,
		},
		{
			MethodName: "GetTrack",
			Handler:    _MusicService_GetTrack_Handler,
		},
		{
			MethodName: "ListTracks",
			Handler:    _MusicService_ListTracks_Handler,
		},
		{
			MethodName: "SearchTracks",
			Handler:    _MusicService_SearchTracks_Handler,
		},
		{
			MethodName: "CreatePlaylist",
			Handler:    _MusicService_CreatePlaylist_Handler,
		},
		{
			MethodName: "AddToPlaylist",
			Handler:    _MusicService_AddToPlaylist_Handler,
		},
		{
			MethodName: "RemoveFromPlaylist",
			Handler:    _MusicService_RemoveFromPlaylist_Handler,
		},
		{
			MethodName: "GetPlaylist",
			Handler:    _MusicService_GetPlaylist_Handler,
		},
		{
			MethodName: "GetUserPlaylists",
			Handler:    _MusicService_GetUserPlaylists_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _MusicService_GetRecommendations_Handler,
		},
		{
			MethodName: "LikeTrack",
			Handler:    _MusicService_LikeTrack_Handler,
		},
		{
			MethodName: "GetLikedTracks",
			Handler:    _MusicService_GetLikedTracks_Handler,
		},
		{
			MethodName: "AddToQueue",
			Handler:    _MusicService_AddToQueue_Handler,
		},
		{
			MethodName: "GetQueue",
			Handler:    _MusicService_GetQueue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTrack",
			Handler:       _MusicService_StreamTrack_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "music.proto",
}
